In [1]:
import pandas as pd
import numpy as np
from Song_Recommendation import df, features_scaled

In [2]:
df = pd.read_csv("spotify-tracks-dataset-detailed.csv")

In [3]:
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  object
 1   artists           113999 non-null  object
 2   album_name        113999 non-null  object
 3   track_name        113999 non-null  object
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 16.6+ MB

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [5]:
df[df.isna().any(axis=1)]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [6]:
df = df.dropna(subset=["artists", "track_name"])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113999 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          113999 non-null  object
 1   artists           113999 non-null  object
 2   album_name        113999 non-null  object
 3   track_name        113999 non-null  object
 4   popularity        113999 non-null  int64
 5   duration_ms       113999 non-null  int64
 6   explicit          113999 non-null  bool
 7   danceability      113999 non-null  float64
 8   energy            113999 non-null  float64
 9   key               113999 non-null  int64
 10  loudness          113999 non-null  float64
 11  mode              113999 non-null  int64
 12  speechiness       113999 non-null  float64
 13  acousticness      113999 non-null  float64
 14  instrumentalness  113999 non-null  float64
 15  liveness          113999 non-null  float64
 16  valence           113999 non-null  float64
 17  tempo             113999 non-null  float64
 18  time_signature    113999 non-null  int64
 19  track_genre       113999 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 17.5+ MB

In [8]:
df.duplicated(subset=["track_name", "artists"]).sum()

np.int64(32656)

In [9]:
df[df.duplicated(subset=["track_name", "artists"], keep=False)][
    ["track_name", "artists"]
].head(20)

                          track_name                               artists
0                             Comedy                           Gen Hoshino
1                   Ghost - Acoustic                          Ben Woodward
3         Can't Help Falling In Love                          Kina Grannis
4                            Hold On                      Chord Overstreet
5               Days I Will Remember                          Tyrone Wells
6                      Say Something  A Great Big World;Christina Aguilera
7                          I'm Yours                            Jason Mraz
8                              Lucky             Jason Mraz;Colbie Caillat
9                             Hunger                        Ross Copperman
10              Give Me Your Forever                          Zack Tabudlo
11                   I Won't Give Up                            Jason Mraz
12                              Solo                              Dan Berk
13                          Bad Liar                         Anna Hamilton
15  Falling in Love at a Coffee Shop                           Landon Pigg
16             ily (i love you baby)                  Andrew Foy;Renee Foy
17                       At My Worst                  Andrew Foy;Renee Foy
18                             Lucky             Jason Mraz;Colbie Caillat
20                         I'm Yours                            Jason Mraz
22                     Say Something  A Great Big World;Christina Aguilera
23                  93 Million Miles                            Jason Mraz

In [10]:
df[
    (df["track_name"] == "I'm Yours") &
    (df["artists"] == "Jason Mraz")
]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.960,4,acoustic
20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.960,4,acoustic
162,03yc0G2OoH1Eeyu7Piy8fK,Jason Mraz,I'm Yours,I'm Yours,60,243494,False,0.693,0.430,11,-9.395,1,0.0442,0.565,0.0,0.0928,0.731,151.001,4,acoustic
91904,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.960,4,rock

In [11]:
df.duplicated().sum()

np.int64(450)

In [12]:
df = df.drop_duplicates()
df.shape

(113549, 20)

In [13]:
df[df["track_name"] == "Comedy"][
    ["track_id", "artists", "album_name", "track_name",
     "popularity", "track_genre", "danceability", "energy",
     "valence", "tempo"]
]

,track_id,artists,album_name,track_name,popularity,track_genre,danceability,energy,valence,tempo
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,acoustic,0.676,0.461,0.715,87.917
62102,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,j-pop,0.676,0.461,0.715,87.917
99152,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,singer-songwriter,0.676,0.461,0.715,87.917
102151,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,songwriter,0.676,0.461,0.715,87.917

In [14]:
df["track_id"].duplicated().sum()

np.int64(23809)

In [15]:
df = df.drop_duplicates(subset="track_id")
df.shape

(89740, 20)

In [16]:
df = df.reset_index(drop=True)

In [17]:
features = df[
    [
        "danceability",
        "energy",
        "loudness",
        "speechiness",
        "acousticness",
        "instrumentalness",
        "liveness",
        "valence",
        "tempo"
    ]
]

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

song_index = 0
song = features_scaled[song_index].reshape(1, -1)
similarities = cosine_similarity(song, features_scaled)[0]

In [20]:
import numpy as np

similar_indices = np.argsort(similarities)[::-1]
similar_indices[:10]

array([    0, 87901,   357, 73712, 26812, 35193,   850, 82137, 87378,
       52241])

In [21]:
recommended_indices = similar_indices[1:6]

In [22]:
recommendations = df.iloc[recommended_indices]
recommendations[["track_name", "artists"]]

                               track_name           artists
87901                            Skylight          Gramatik
357    Look For The Good (Single Version)        Jason Mraz
73712                 That Certain Female  Charlie Feathers
26812                       Monde de fous           Danakil
35193                           Blink 182            Trille

In [23]:
df[df["track_name"] == "I'm Yours"]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.960,4,acoustic
20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.960,4,acoustic
162,03yc0G2OoH1Eeyu7Piy8fK,Jason Mraz,I'm Yours,I'm Yours,60,243494,False,0.693,0.430,11,-9.395,1,0.0442,0.565,0.0,0.0928,0.731,151.001,4,acoustic

In [24]:
song = df[df["track_name"] == "I'm Yours"].iloc[0]

In [25]:
song

track_id                         1EzrEOXmMH3G43AXT1y7pA
artists                                      Jason Mraz
album_name          We Sing. We Dance. We Steal Things.
track_name                                    I'm Yours
popularity                                           80
duration_ms                                      242946
explicit                                          False
danceability                                      0.703
energy                                            0.444
key                                                  11
loudness                                         -9.331
mode                                                  1
speechiness                                      0.0417
acousticness                                      0.559
instrumentalness                                    0.0
liveness                                         0.0973
valence                                           0.712
tempo                                            150.96
time_signature                                        4
track_genre                                    acoustic
Name: 7, dtype: object

In [26]:
song_index = song.name

In [27]:
song_features = features_scaled[song_index].reshape(1, -1)
similarities = cosine_similarity(song_features, features_scaled)[0]

In [28]:
similar_indices = np.argsort(similarities)[::-1]
recommended_indices = similar_indices[1:6]
recommendations = df.iloc[recommended_indices]
recommendations[["track_name", "artists"]]

        track_name       artists
7        I'm Yours    Jason Mraz
162      I'm Yours    Jason Mraz
34139        Duele         NAFTA
3204   Yasss Queen     Baby Tate
35303   Lemon Tree  Fools Garden

In [29]:
def recommend_songs(song_name = None, track_id = None):
    if track_id is not None:
        song = df[df["track_id"] == track_id]
    else:
        song = df[df["track_name"] == song_name]
    if song.shape[0] == 0:
        return "Song Does Not Exist"
    if track_id is None and song.shape[0] > 1:
        return song[["track_name", "artists", "track_id"]]
    song = song.iloc[0]
    song_index = song.name
    song_features = features_scaled[song_index].reshape(1, -1)
    similarities = cosine_similarity(song_features, features_scaled)[0]
    similarities[song_index] = -np.inf
    recommended_indices = np.argsort(similarities)[::-1]
    recommended_scores = similarities[recommended_indices]
    recommendations = df.iloc[recommended_indices].copy()
    recommendations["Similarity"] = recommended_scores
    recommendations["Similarity"] = recommendations["Similarity"].round(3)
    recommendations = recommendations.drop_duplicates(subset=["track_name", "artists"])
    recommendations = recommendations[~((recommendations["track_name"] == song["track_name"]) & (recommendations["artists"] == song["artists"]))]
    return recommendations[["track_name", "artists", "Similarity"]][:5]

recommend_songs("Duele")

                      track_name                         artists  Similarity
162                    I'm Yours                      Jason Mraz       0.988
46269    I Won't Be Home No More  Hank Williams;Drifting Cowboys       0.986
46429           Time's a Wastin'     Carl Smith;June Carter Cash       0.983
13273          Rain Rain Go Away                       CoComelon       0.980
46042  Settin' The Woods On Fire  Hank Williams;Drifting Cowboys       0.979

In [33]:
def genre_at_k(seed_index, k=10):
    sims = cosine_similarity(features_scaled[seed_index].reshape(1, -1), features_scaled)[0]
    sims[seed_index] = -np.inf
    top_idx = np.argsort(sims)[::-1][:k]
    seed_genre = df.loc[seed_index, "track_genre"]
    rec_genres = df.loc[top_idx, "track_genre"]
    return (rec_genres == seed_genre).sum() / len(rec_genres)

def genre_at_k_baseline(seed_index, k=10):
    sims = cosine_similarity(features_scaled[seed_index].reshape(1, -1), features_scaled)[0]
    sims[seed_index] = -np.inf
    top_idx = np.random.choice(len(df), k, replace=False)
    seed_genre = df.loc[seed_index, "track_genre"]
    rec_genres = df.loc[top_idx, "track_genre"]
    return (rec_genres == seed_genre).sum() / len(rec_genres)

seeds = df.sample(300, random_state=42).index
model_score = np.mean([genre_at_k(i) for i in seeds])
print("model:", model_score)

baseline_score = np.mean([genre_at_k_baseline(i) for i in seeds])
print("baseline:", baseline_score)

model: 0.152
baseline: 0.008000000000000002